# Generated by Django 5.1.5 on 2025-01-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_user_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pencil_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
