# Generated by Django 5.0.6 on 2025-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_casino_manager_pencil_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='day_end',
            field=models.TimeField(default='17:30'),
        ),
        migrations.AddField(
            model_name='casino',
            name='day_start',
            field=models.TimeField(default='09:30'),
        ),
        migrations.AddField(
            model_name='casino',
            name='grave_end',
            field=models.TimeField(default='09:30'),
        ),
        migrations.AddField(
            model_name='casino',
            name='grave_start',
            field=models.TimeField(default='01:30'),
        ),
        migrations.AddField(
            model_name='casino',
            name='swing_end',
            field=models.TimeField(default='01:30'),
        ),
        migrations.AddField(
            model_name='casino',
            name='swing_start',
            field=models.TimeField(default='17:30'),
        ),
    ]
