# Generated by Django 5.0.6 on 2025-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_toke_signoff_hours_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokesignoff',
            name='toke_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final toke distribution hours', max_digits=5, null=True),
        ),
    ]
