# Generated by Django 5.0.6 on 2025-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_tokesignoff_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokes',
            name='is_collection_day',
            field=models.BooleanField(default=True, help_text='True if this is a collection day, False if distribution day'),
        ),
    ]
